### ISSUE TITLE
Changes made don't stick

### ISSUE THREAD

**Issue by RandomMan25XX** [FoofooTheGuy/Miichanic_Plugin#1]
I'm not sure if it's just me not understanding how to use the plugin or what, but any changes I make (giving a mii that can't be shared the ability to be shared, giving a mii gold pants, etc.) No matter what I do all of that is reverted when I restart the app, no amount of dumping and reimporting of saves has changed that either

**Comment by FoofooTheGuy** [comment]
> I'm not sure if it's just me not understanding how to use the plugin or what, but any changes I make (giving a mii that can't be shared the ability to be shared, giving a mii gold pants, etc.) No matter what I do all of that is reverted when I restart the app, no amount of dumping and reimporting of saves has changed that either

You will have to make the game save to, well, save the changes you make using cheats. Some ways of having it save are by creating a new Mii, erasing a Mii, or making changes to a Mii using the editor and saving that. That goes the same for restoring a save file. Oh, forgot to mention: When you close the app and it says it's saving the data, it isn't actually saving anything :flushed:
